# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    (1..2).each do |i|
        config.vm.define vm_name = "ldap#{i}" do |config|
            config.vm.hostname = "ldap#{i}"
            config.vm.network :private_network, ip: "192.168.9.#{i+100}"
        end
    end

    config.vm.define vm_name = "consumer" do |config|
        config.vm.hostname = "consumer"
        config.vm.network :private_network, ip: "192.168.9.103"
    end
end
